//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiCuaHang.Areas.Manager.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class DONVITINH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONVITINH()
        {
            this.LOAISANPHAMs = new HashSet<LOAISANPHAM>();
        }
        [Key]
        public int MaDVT { get; set; }
        [DisplayName("Tên đơn vị tính")]
        [Required(ErrorMessage = "Tên đơn vị tính không được phép rỗng")]
        [StringLength(10, ErrorMessage = "Tên đơn vị tính không quá 10 kí tự")]
        [Remote("IsTenDVTavailable", "DVT", ErrorMessage = "Tên đơn vị tính này đã tồn tại")]
        public string TenDVT { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LOAISANPHAM> LOAISANPHAMs { get; set; }
    }
}