
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace QuanLiCuaHang.Areas.Manager.Data
{

using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class LOAIDV
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public LOAIDV()
    {

        this.CHITIET_PHIEUDV = new HashSet<CHITIET_PHIEUDV>();

    }
    [Key]

    public int MaLoaiDV { get; set; }

        [Display(Name = "Tên loại dịch vụ")]
        [Required(ErrorMessage = "Tên loại dịch vụ trống")]
        [Remote("IsTenDVAvailable", "SanPham", ErrorMessage = "Tên loại dịch vụ đã có rồi !")]

        public string TenLoaiDV { get; set; }

        [Required(ErrorMessage = "Đơn giá dịch vụ trống")]
        [Range(1, Int32.MaxValue, ErrorMessage = "Đơn giá dịch vụ phải lớn hơn 0")]
        public decimal DonGiaDV { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<CHITIET_PHIEUDV> CHITIET_PHIEUDV { get; set; }

}

}
