//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiCuaHang.Areas.Manager.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class NHACUNGCAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHACUNGCAP()
        {
            this.PHIEUMUAHANGs = new HashSet<PHIEUMUAHANG>();
        }
        [Key]
        public int MaNCC { get; set; }

        [DisplayName("Tên nhà cung cấp")]
        [Required(ErrorMessage = "Tên nhà cung cấp không được phép rỗng")]
        [StringLength(30, ErrorMessage = "Tên nhà cung cấp không quá 30 kí tự")]
        [Remote("IsTenNhaCCavailable", "NhaCungCap", ErrorMessage = " Nhà cung cấp này đã tồn tại")]
        public string TenNCC { get; set; }

        [DisplayName("Địa chỉ")]
        [Required(ErrorMessage = "Địa chỉ nhà cung cấp không được phép rỗng")]
        [Remote("IsDiaChiavailable", "NhaCungCap", ErrorMessage = " Địa chỉ này đã tồn tại")]
        public string DiaChi { get; set; }


        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Số điện thoại")]
        [Remote("IsSDTavailable", "NhaCungCap", ErrorMessage = "Số điện thoại này đã tồn tại")]
        [Required(ErrorMessage = "Số điện thoại nhà cung cấp không được phép rỗng")]
        [RegularExpression(@"^\(?([0-9]{3})\)?([0-9]{3})[-. ]?([0-9]{4})$",
                   ErrorMessage = "Số điện thoại phải là 10 số")]
        public string SDT { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHIEUMUAHANG> PHIEUMUAHANGs { get; set; }


    }
}