//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiCuaHang.Areas.Manager.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.BCTONKHOes = new HashSet<BCTONKHO>();
            this.CHITIET_PMH = new HashSet<CHITIET_PMH>();
            this.CT_PHIEUBANHANG = new HashSet<CT_PHIEUBANHANG>();
        }



        [Key]
        public int MaSP { get; set; }
        [Display(Name = "Tên sản phẩm")]
        [Required(ErrorMessage = "Tên sản phẩm trống")]
        [Remote("IsTenSPAvailable", "SanPham", ErrorMessage = "Tên sản phẩm đã có rồi !")]
        public string TenSanPham { get; set; }

        [Required(ErrorMessage = "Giá mua vào trống")]
        [Range(1, Int32.MaxValue, ErrorMessage = "Giá mua vào phải lớn hơn 0" )]
        public decimal GiaMuaVao { get; set; }

        [Required(ErrorMessage = "Giá bán ra trống")]
        public decimal GiaBanRa { get; set; }


        [Required(ErrorMessage = "Số lượng tồn trống")]
        public int SoLuongTon { get; set; }

        [Display(Name = "Tên loại sản phẩm")]
        [Required(ErrorMessage = "Tên loại sản phẩm trống")]
        public int MaLoaiSP { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BCTONKHO> BCTONKHOes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_PMH> CHITIET_PMH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PHIEUBANHANG> CT_PHIEUBANHANG { get; set; }
        public virtual LOAISANPHAM LOAISANPHAM { get; set; }
    }
}
